platform :ios, '6.0'
pod 'SIAlertView'
pod 'MMDrawerController'
pod 'RETableViewManager'
pod 'AFNetworking'
pod 'Facebook-iOS-SDK'
pod 'google-plus-ios-sdk'
pod 'SVProgressHUD'
pod 'NewRelicAgent'
pod 'TSMiniWebBrowser'
pod 'MoPubSDK'
pod 'FontAwesomeKit'
pod 'MKSlidingTableViewCell'