platform :ios, '6.0'
pod 'SIAlertView'
pod 'MMDrawerController'
pod 'RETableViewManager'
pod 'AFNetworking', '1.3.3'
pod 'Facebook-iOS-SDK'
pod 'google-plus-ios-sdk' , '1.3.0'
pod 'SVProgressHUD'
pod 'NewRelicAgent'
pod 'TSMiniWebBrowser'
pod 'MoPubSDK'
pod 'FontAwesomeKit'
pod 'MKSlidingTableViewCell'
pod 'EAIntroView'
